language: python
python:
  - '2.7'
  - '3.6'
before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin
  - sudo mkdir ~/.config/earthengine
  - sudo echo '{"refresh_token": "'$EE_KEY'"}' > ~/.config/earthengine/credentials
install:
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" gdal==$(gdal-config --version)
  - pip install -r requirements.txt
  - pip install .
script: pytest